version: '3'
services:
  postgredb:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: postgreSQL
    volumes:
      - ./postgres:/var/lib/postgresql/data
